title: "BuildingBloCS"
tagline: "High School Computing Conference"
date: "Date TBC"
location: "Location TBC"
instagram: "buildingblocs22"
github: "buildingblocs"
discord: "D2ur6KJPxK"

exclude:
  - README.md
  - assets/sass
  - package.json
  - node_modules/
  - Gruntfile.js
  - .jekyll-cache/
  - .template/
