title: "BuildingBloCS"
tagline: "High School Computing Conference"
date: "Date TBC"
location: "Location TBC"
instagram: "buildingblocs22"
github: "buildingblocs"
discord: "D2ur6KJPxK"

# For jekyll-multiple-languages-plugin
# See: https://github.com/kurtsson/jekyll-multiple-languages-plugin
languages: ["en", "jp", "zh"]
exclude_from_localisations: ["javascript", "images", "css", "sass"]

exclude:
  - README.md
  - assets/sass
  - package.json
  - node_modules/
  - Gruntfile.js
  - .jekyll-cache/
  - .template/
